export const S = {
  root:      { minHeight: '100vh', background: '#F5F3EE', color: '#1a1a1a', fontFamily: "'Georgia', serif", position: 'relative' },
  bgPattern: { position: 'fixed', inset: 0, backgroundImage: 'radial-gradient(circle at 20% 50%, #FFF8E7 0%, transparent 55%), radial-gradient(circle at 80% 20%, #E8F6F5 0%, transparent 55%)', pointerEvents: 'none', zIndex: 0 },

  header:       { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '14px 24px', borderBottom: '1px solid #E0DBD0', position: 'relative', zIndex: 10, background: '#FFFDF8', flexWrap: 'wrap', gap: 10 },
  logoTitle:    { fontSize: 20, fontWeight: 700, letterSpacing: 3, color: '#1a1a1a' },
  logoSub:      { fontSize: 10, color: '#999', letterSpacing: 2, textTransform: 'uppercase' },

  userBadge:  { display: 'flex', alignItems: 'center', gap: 10, padding: '6px 12px', background: '#F5F3EE', border: '1px solid #E0DBD0', borderRadius: 10 },
  userAvatar: { width: 32, height: 32, borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 12, fontWeight: 700 },
  userName:   { fontSize: 13, fontWeight: 700, color: '#1a1a1a' },
  userRole:   { fontSize: 11, color: '#aaa' },
  logoutBtn:  { padding: '7px 14px', background: 'transparent', border: '1px solid #D5CFC4', color: '#888', borderRadius: 8, cursor: 'pointer', fontSize: 12, fontFamily: 'inherit' },

  bellBtn:   { position: 'relative', padding: '8px 10px', background: 'transparent', border: '1px solid #D5CFC4', borderRadius: 8, cursor: 'pointer', fontSize: 18, lineHeight: 1 },
  bellBadge: { position: 'absolute', top: -6, right: -6, background: '#E07070', color: '#fff', fontSize: 10, fontWeight: 700, borderRadius: 10, padding: '2px 5px', minWidth: 16, textAlign: 'center', lineHeight: '14px' },

  notifPanel:      { position: 'absolute', top: 'calc(100% + 8px)', right: 0, width: 340, background: '#FFFDF8', border: '1px solid #E0DBD0', borderRadius: 14, boxShadow: '0 8px 32px rgba(0,0,0,0.12)', zIndex: 200, overflow: 'hidden' },
  notifPanelHdr:   { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '14px 16px 10px', borderBottom: '1px solid #EDE8DF' },
  notifPanelTitle: { fontSize: 14, fontWeight: 700, color: '#1a1a1a' },
  notifMarkAll:    { padding: '3px 10px', background: 'transparent', border: '1px solid #D5CFC4', borderRadius: 6, cursor: 'pointer', fontSize: 11, color: '#888', fontFamily: 'inherit' },
  notifEmpty:      { padding: '24px 16px', textAlign: 'center', color: '#bbb', fontSize: 13, fontStyle: 'italic' },
  notifList:       { maxHeight: 360, overflowY: 'auto' },
  notifItem:       { display: 'flex', alignItems: 'flex-start', gap: 10, padding: '12px 14px', borderBottom: '1px solid #F0EDE6' },
  notifDot:        { width: 8, height: 8, borderRadius: '50%', flexShrink: 0, marginTop: 5 },
  notifBody:       { flex: 1, minWidth: 0 },
  notifIcon:       { fontSize: 16, marginBottom: 3 },
  notifText:       { fontSize: 12, color: '#333', lineHeight: 1.5, marginBottom: 3 },
  notifTime:       { fontSize: 10, color: '#bbb' },
  notifDismiss:    { background: 'transparent', border: 'none', color: '#ccc', cursor: 'pointer', fontSize: 13, padding: '2px 4px', flexShrink: 0 },

  statsBar: { display: 'flex', gap: 1, background: '#FFFDF8', borderBottom: '1px solid #E0DBD0', position: 'relative', zIndex: 1, overflowX: 'auto' },
  statCard: { flex: 1, minWidth: 110, display: 'flex', alignItems: 'center', gap: 8, padding: '10px 14px', borderRight: '1px solid #E0DBD0' },
  statNum:  { fontSize: 15, fontWeight: 700, color: '#1a1a1a' },
  statChip: { marginLeft: 'auto', fontSize: 11, color: '#888', background: '#EDE8DF', padding: '2px 8px', borderRadius: 10 },

  main:    { position: 'relative', zIndex: 1, maxWidth: 1100, margin: '0 auto', padding: '0 16px 40px' },
  content: { paddingTop: 20 },

  tabBar:     { display: 'flex', gap: 0, marginBottom: 20, borderBottom: '2px solid #E0DBD0' },
  tab:        { padding: '9px 20px', background: 'transparent', border: 'none', color: '#aaa', cursor: 'pointer', fontSize: 13, fontFamily: 'inherit', borderBottom: '2px solid transparent', marginBottom: -2 },
  tabActive:  { padding: '9px 20px', background: 'transparent', border: 'none', color: '#C8960A', cursor: 'pointer', fontSize: 13, fontWeight: 700, fontFamily: 'inherit', borderBottom: '2px solid #C8960A', marginBottom: -2 },
  tab2:       { padding: '7px 16px', background: 'transparent', border: 'none', color: '#bbb', cursor: 'pointer', fontSize: 12, fontFamily: 'inherit', borderBottom: '2px solid transparent', marginBottom: -2 },
  tabActive2: { padding: '7px 16px', background: 'transparent', border: 'none', color: '#6B8FB5', cursor: 'pointer', fontSize: 12, fontWeight: 700, fontFamily: 'inherit', borderBottom: '2px solid #6B8FB5', marginBottom: -2 },

  sectionHeader: { display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 20, gap: 12, flexWrap: 'wrap' },
  sectionTitle:  { fontSize: 20, fontWeight: 700, color: '#1a1a1a', marginBottom: 10, letterSpacing: 1 },
  subTitle:      { fontSize: 16, color: '#888', marginBottom: 12, marginTop: 24, letterSpacing: 1 },
  filterRow:     { display: 'flex', gap: 6, flexWrap: 'wrap' },
  filterBtn:     { padding: '5px 14px', background: 'transparent', border: '1px solid #D5CFC4', color: '#999', borderRadius: 20, cursor: 'pointer', fontSize: 12, fontFamily: 'inherit' },
  filterActive:  { padding: '5px 14px', background: '#1a1a1a', border: '1px solid #1a1a1a', color: '#fff', borderRadius: 20, cursor: 'pointer', fontSize: 12, fontFamily: 'inherit' },
  actionBtns:    { display: 'flex', gap: 8, flexWrap: 'wrap' },
  addBtn:        { padding: '9px 18px', background: '#C8960A', border: 'none', color: '#fff', borderRadius: 8, cursor: 'pointer', fontSize: 13, fontWeight: 700, fontFamily: 'inherit', whiteSpace: 'nowrap' },

  shiftGrid:    { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))', gap: 14 },
  shiftCard:    { background: '#FFFDF8', border: '1px solid #E0DBD0', borderRadius: 10, padding: 16, boxShadow: '0 2px 8px rgba(0,0,0,0.05)' },
  shiftCardTop: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 8 },
  shiftMeta:    { display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' },
  catBadge:     { fontSize: 11, padding: '2px 8px', borderRadius: 10, fontWeight: 700, letterSpacing: 0.5 },
  shiftDateSm:  { fontSize: 12, color: '#999' },
  shiftName:    { fontSize: 17, fontWeight: 700, marginBottom: 4, color: '#1a1a1a' },
  shiftTime:    { fontSize: 13, color: '#888', marginBottom: 8 },
  roomBadge:    { display: 'inline-flex', alignItems: 'center', gap: 4, fontSize: 11, padding: '3px 10px', borderRadius: 10, background: '#6B8FB522', color: '#4a6f95', fontWeight: 600, border: '1px solid #6B8FB544' },
  editRoomBtn:  { padding: '2px 6px', background: 'transparent', border: '1px solid #E0DBD0', borderRadius: 6, cursor: 'pointer', fontSize: 11, color: '#bbb' },
  roomPicker:      { background: '#F5F3EE', border: '1px solid #E0DBD0', borderRadius: 8, padding: '10px 12px', marginBottom: 10 },
  roomPickerLabel: { fontSize: 11, color: '#aaa', letterSpacing: 1, textTransform: 'uppercase', marginBottom: 8 },
  rpOpt:       { display: 'inline-block', margin: '3px 4px 3px 0', padding: '5px 12px', background: '#FFFDF8', border: '1px solid #D5CFC4', borderRadius: 16, cursor: 'pointer', fontSize: 12, fontFamily: 'inherit', color: '#555' },
  rpOptActive: { background: '#6B8FB522', border: '1px solid #6B8FB5', color: '#4a6f95', fontWeight: 700 },
  rpCancel:    { display: 'block', marginTop: 8, padding: '4px 12px', background: 'transparent', border: '1px solid #D5CFC4', borderRadius: 6, cursor: 'pointer', fontSize: 11, color: '#aaa', fontFamily: 'inherit' },
  deleteBtn:     { background: 'transparent', border: 'none', color: '#bbb', cursor: 'pointer', fontSize: 13, padding: 2, lineHeight: 1 },
  assignedBox:   { display: 'flex', alignItems: 'center', gap: 8, background: '#EDF7F0', borderRadius: 8, padding: '10px 12px' },
  assignedName:  { fontSize: 14, fontWeight: 600, flex: 1, color: '#1a1a1a' },
  assignedBadge: { fontSize: 11, color: '#2A9D6E', background: '#2A9D6E22', padding: '2px 8px', borderRadius: 10 },
  unassignBtn:   { background: 'transparent', border: '1px solid #D5CFC4', color: '#aaa', borderRadius: 6, cursor: 'pointer', fontSize: 13, padding: '2px 7px', lineHeight: 1, fontFamily: 'inherit' },
  applicantsBox:   { borderTop: '1px solid #EDE8DF', paddingTop: 10 },
  applicantsLabel: { fontSize: 12, color: '#aaa', marginBottom: 8 },
  noApplicants:    { fontSize: 12, color: '#bbb', fontStyle: 'italic' },
  applicantRow:    { display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 },
  applicantInfo:   { flex: 1 },
  applicantName:   { fontSize: 13, fontWeight: 600, color: '#1a1a1a' },
  assignBtn:       { padding: '4px 10px', background: 'transparent', border: '1px solid', borderRadius: 6, cursor: 'pointer', fontSize: 11, fontFamily: 'inherit' },
  empAvatar:       { width: 34, height: 34, borderRadius: '50%', background: '#EDE8DF', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 12, fontWeight: 700, flexShrink: 0, color: '#555' },
  applicantsCount: { fontSize: 12, color: '#aaa', marginBottom: 10 },
  applyBtn:        { width: '100%', padding: '9px', border: 'none', borderRadius: 8, color: '#fff', fontWeight: 700, cursor: 'pointer', fontSize: 13, fontFamily: 'inherit' },
  withdrawBtn:     { width: '100%', padding: '9px', background: 'transparent', border: '1px solid #D5CFC4', borderRadius: 8, color: '#aaa', cursor: 'pointer', fontSize: 13, fontFamily: 'inherit' },

  empGrid:     { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))', gap: 12 },
  empCard:     { background: '#FFFDF8', border: '1px solid #E0DBD0', borderRadius: 10, padding: 16, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 6, textAlign: 'center', boxShadow: '0 2px 6px rgba(0,0,0,0.04)' },
  empAvatarLg: { width: 48, height: 48, borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 16, fontWeight: 700 },
  empName:     { fontSize: 13, fontWeight: 700, color: '#1a1a1a' },
  empNotifDot: { position: 'absolute', top: -4, right: -4, background: '#E07070', color: '#fff', fontSize: 9, fontWeight: 700, borderRadius: 10, padding: '1px 4px', minWidth: 14, textAlign: 'center', lineHeight: '14px' },

  profileBanner: { display: 'flex', alignItems: 'center', gap: 16, background: '#FFFDF8', border: '1px solid #E0DBD0', borderRadius: 10, padding: '16px 20px', marginBottom: 16, flexWrap: 'wrap', boxShadow: '0 2px 8px rgba(0,0,0,0.05)' },
  profileName:   { fontSize: 20, fontWeight: 700, marginBottom: 4, color: '#1a1a1a' },

  accSection:      { background: '#FFFDF8', border: '1px solid #E0DBD0', borderRadius: 12, padding: '16px 18px', boxShadow: '0 2px 6px rgba(0,0,0,0.04)' },
  accSectionTitle: { fontSize: 13, fontWeight: 700, color: '#888', letterSpacing: 1, textTransform: 'uppercase', marginBottom: 14 },
  accRow:          { display: 'flex', alignItems: 'center', gap: 12, padding: '10px 0', borderBottom: '1px solid #F0EDE6' },
  accAvatar:       { width: 38, height: 38, borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 13, fontWeight: 700, flexShrink: 0 },
  accInfo:         { flex: 1, minWidth: 0 },
  accName:         { fontSize: 14, fontWeight: 700, color: '#1a1a1a', marginBottom: 2 },
  accRole:         { fontSize: 11, color: '#aaa', display: 'flex', alignItems: 'center', gap: 4 },
  accEditBtn:      { padding: '5px 12px', background: 'transparent', border: '1px solid #D5CFC4', borderRadius: 6, cursor: 'pointer', fontSize: 11, color: '#666', fontFamily: 'inherit', whiteSpace: 'nowrap' },
  accDeleteBtn:    { background: 'transparent', border: 'none', color: '#ddd', cursor: 'pointer', fontSize: 15, padding: '2px 4px' },
  accErrorBox:     { marginTop: 12, padding: '8px 12px', background: '#FFF0F0', border: '1px solid #F5C6C6', borderRadius: 8, fontSize: 12, color: '#E07070' },

  calNav:      { display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14, gap: 8, flexWrap: 'wrap' },
  calNavBtn:   { padding: '7px 16px', background: '#FFFDF8', border: '1px solid #D5CFC4', borderRadius: 8, cursor: 'pointer', fontSize: 13, fontFamily: 'inherit', color: '#555' },
  calNavTitle: { fontSize: 15, fontWeight: 700, color: '#1a1a1a', textAlign: 'center', flex: 1 },
  calGrid:     { display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: 6 },
  calDay:      { background: '#FFFDF8', border: '1px solid #E0DBD0', borderRadius: 10, padding: '8px 6px', minHeight: 110, boxShadow: '0 1px 4px rgba(0,0,0,0.04)' },
  calDayToday: { border: '2px solid #C8960A', background: '#FFFBF0' },
  calDayHdr:   { display: 'flex', flexDirection: 'column', alignItems: 'center', marginBottom: 6, gap: 1 },
  calDayName:  { fontSize: 10, color: '#aaa', textTransform: 'uppercase', letterSpacing: 1 },
  calDayNum:   { fontSize: 18, fontWeight: 700, color: '#1a1a1a', lineHeight: 1 },
  calEmpty:    { fontSize: 11, color: '#ddd', textAlign: 'center', marginTop: 8 },
  calShift:    { borderRadius: 6, padding: '5px 6px', marginBottom: 4, cursor: 'pointer' },

  overlay:      { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.35)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 100, padding: 16 },
  modal:        { background: '#FFFDF8', border: '1px solid #E0DBD0', borderRadius: 14, padding: '28px 24px', width: '100%', maxWidth: 400, boxShadow: '0 8px 40px rgba(0,0,0,0.12)', maxHeight: '90vh', overflowY: 'auto' },
  modalTitle:   { fontSize: 18, fontWeight: 700, marginBottom: 18, color: '#C8960A' },
  label:        { display: 'block', fontSize: 11, color: '#aaa', letterSpacing: 1, textTransform: 'uppercase', marginBottom: 6, marginTop: 14 },
  input:        { width: '100%', padding: '10px 12px', background: '#F5F3EE', border: '1px solid #D5CFC4', borderRadius: 8, color: '#1a1a1a', fontSize: 14, fontFamily: 'inherit', boxSizing: 'border-box' },
  catSelect:    { display: 'flex', gap: 8, flexWrap: 'wrap', marginTop: 6 },
  catBtn:       { padding: '8px 14px', background: '#F0EDE6', border: '1px solid #D5CFC4', color: '#888', borderRadius: 8, cursor: 'pointer', fontSize: 13, fontFamily: 'inherit' },
  modalActions: { display: 'flex', gap: 10, marginTop: 22 },
  cancelBtn:    { flex: 1, padding: '10px', background: 'transparent', border: '1px solid #D5CFC4', color: '#aaa', borderRadius: 8, cursor: 'pointer', fontFamily: 'inherit', fontSize: 13 },
  confirmBtn:   { flex: 1, padding: '10px', background: '#C8960A', border: 'none', color: '#fff', borderRadius: 8, cursor: 'pointer', fontWeight: 700, fontFamily: 'inherit', fontSize: 13 },
  toast:        { position: 'fixed', bottom: 28, left: '50%', transform: 'translateX(-50%)', background: '#1a1a1a', color: '#fff', padding: '10px 24px', borderRadius: 20, fontWeight: 700, fontSize: 14, zIndex: 200, whiteSpace: 'nowrap', boxShadow: '0 4px 20px rgba(0,0,0,0.2)' },
  empty:        { color: '#bbb', fontStyle: 'italic', padding: 20, gridColumn: '1/-1' },

  spinner:     { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', minHeight: '100vh', background: '#F5F3EE', gap: 16, fontFamily: "'Georgia', serif" },
  spinnerIcon: { fontSize: 48, animation: 'spin 1.5s linear infinite' },
  spinnerText: { fontSize: 14, color: '#aaa' },
}
